package com.example.cit0rustest.repository

import com.example.cit0rustest.vm.GroupViewModel
import com.example.cit0rustest.vm.ItemViewModel
import com.example.cit0rustest.vm.LayerViewModel

class LayerDataProvider {
    fun getLayersListData(): List<ItemViewModel> {
        return listOf<ItemViewModel> (
            LayerViewModel(
                "Слой 1",
                2,
                5,
                16..17,
                "12.12.12",
                false,
                true,

            ),
            LayerViewModel(
                "Слой 2",
                2,
                5,
                16..17,
                "12.12.12",
                true,
                true,

                ),
            LayerViewModel(
                "Слой 3",
                2,
                5,
                16..17,
                "12.12.12",
                false,
                false,
            ),
            GroupViewModel("Общие слои"),
            LayerViewModel(
                "Слой 4",
                2,
                5,
                16..17,
                "12.12.12",
                true,
                true,
            ),
            LayerViewModel(
                "Слой 5",
                2,
                5,
                16..17,
                "12.12.12",
                true,
                true,
            ),
            LayerViewModel(
                "Слой 6",
                2,
                5,
                16..17,
                "12.12.12",
                true,
                true,
            ),
            LayerViewModel(
                "Слой 7",
                2,
                5,
                16..17,
                "12.12.12",
                true,
                true,
            ),
            LayerViewModel(
                "Слой 8",
                2,
                5,
                16..17,
                "12.12.12",
                true,
                true,
            ),

            LayerViewModel("слой 9",
            0,
                0,
                0..2,
                "21.04.22",
                true,
                false,
            ),
            LayerViewModel("слой 9",
                5,
                0,
                0..2,
                "13.12.22",
                true,
                true,
            ),
            GroupViewModel("группа"
            ),
            LayerViewModel("слой 10",
                5,
                0,
                0..2,
                "13.12.22",
                true,
                true,
            ),
            LayerViewModel("слой 11",
                5,
                0,
                0..2,
                "13.12.22",
                true,
                true,

            ),
            LayerViewModel("слой 12",
                5,
                0,
                0..2,
                "13.12.22",
                true,
                true,

            ),
            LayerViewModel("слой 13",
                5,
                0,
                0..2,
                "13.12.22",
                true,
                true,

            ),
            LayerViewModel("слой 14",
                5,
                0,
                0..2,
                "13.12.22",
                true,
                true,

            ),
            LayerViewModel("слой 15",
                5,
                0,
                0..2,
                "13.12.22",
                true,
                true,

            )
        )
    }
}